---
title: "week1 arboritum anaysis"
author: "Ben"
date: "9/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(ggrepel)
```

```{r read in data}
#read in data 
one <- read_csv("w1_fieldmethodsdata.csv", guess_max = 40)

```

```{r data cleaning}
#reformat variable names
one <- clean_names(one)
#rename Oak to oak for consistency 
one$genus_of_closest_canopy_tree <- one$genus_of_closest_canopy_tree %>% recode(Oak = "oak")
# rename NAs for consistency 
one[one == "N/A"] <- NA
#check data 
glimpse(one)
#change seedlings type from chr to int
one$number_of_seedlings <- as.integer(one$number_of_seedlings)

```
I need to get the count of seedlings regardless of species and join that with needed data CANOPY COVER, LIGHT INTENSTY, SOIL DEPTH
```{r fix for data that is seperated by plot}
one
#create data frame for number of seedlings by plot ignoring species
sum_seeds <- one %>% group_by(plot_number)%>%summarise(seedling_count = sum(number_of_seedlings))
#c
ind <- one %>% select(plot_number, canopy_cover_percent, light_intensity_lux, soil_depth_cm) 
ind <- unique(ind)
oned <- left_join(sum_seeds, ind, by = "plot_number", )
```

```{r graph of seedling density as a function of percent canopy cover}
# not sure what is meant by seedling density? Should I divide by 1 meter?
ggplot(data = subset.data.frame(oned, !is.na(seedling_count)),aes(x = canopy_cover_percent, y = seedling_count, label = plot_number))+geom_point()+geom_smooth(method = lm)+labs(y = "Seedling Count (# by plot)", x = "% Canopy Cover")+geom_label_repel(box.padding = .5)
ggsave("canopy.png")

lm(oned$seedling_count ~ oned$canopy_cover_percent)%>%summary()
```

```{r graph of seedling density as a function of light intensity}
ggplot(data = subset.data.frame(oned, !is.na(seedling_count)),aes(x = light_intensity_lux , y = seedling_count,label = plot_number))+geom_point()+geom_smooth(method = "lm")+labs(y = "Seedling Count (# by plot)", x = "Light Intensity (Lux)")+geom_label_repel(box.padding = .5)
ggsave("lux.png")

lm(oned$seedling_count ~ oned$light_intensity_lux)%>%summary()
```

```{r graph of seedling density as a function of soil depth}
ggplot(data = subset.data.frame(oned, !is.na(seedling_count)),aes(x = soil_depth_cm , y = seedling_count,label = plot_number))+geom_point()+geom_smooth(method = lm)+labs(y = "Seedling Count (# by plot)", x = "Soil Depth (cm)")+geom_label_repel(box.padding = .5)
ggsave("soil.png")

attach(oned)
lm(oned$seedling_count ~ oned$soil_depth_cm)%>%summary()
```

```{r}
lm(oned$seedling_count ~ oned$light_intensity_lux + oned$canopy_cover_percent)%>% summary()
```


