---
title: "w4_analysis"
author: "Ben"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(ggrepel)
library(gt)
library(grid)
library(broom)
library(lemon)

```

```{r}
treez <-  read_csv("w4/hurricane.csv")


liltrees <- read_csv("w4/hurricane_saplings.csv")

```

```{r clean col names}
treez <- clean_names(treez)

liltrees <- clean_names(liltrees)
```

```{r clean column types}
sapply(treez, class)

#convert dbh and azimuth to numeric
treez <- treez %>% mutate (degrees = parse_number(azimuth_degrees), dbh_cm = parse_number(dbh_cm_or_sap))

liltrees <- liltrees %>% mutate (sap_count = parse_number(sapling_count), seedlin_count = parse_number(seedling_count))
```

```{r make consistent values}
sapply(treez, unique)


treez %>% group_by(genus) %>% summarise( n = n())

treez <- treez %>% mutate( genus = recode(genus,
                                 B = "unknown",
                                 Beach = "beech",
                                 Beech= "beech", 
                                 "Bir ch" = "birch",
                                 Birch = "birch",
                                 "Dead?" = "unknown",
                                 "Oak" = "oak",
                                 "OAK" = "oak",
                                 oube = "unknown",
                                 "PB" = "birch",
                                 "Pine" = "pine",
                                 RM = "maple",
                                 SM = "maple",
                                 Maple = "maple",
                                 Unknown = "unknown",
                                 WP = "pine"
                                 ))


treez$standing_fallen %>% unique()

#recode standing fallen variable 
treez <- treez %>% mutate(standing_fallen = recode(standing_fallen,
                                          "F" = "Fallen",
                                          "f" = "Fallen",
                                          "S" = "Standing",
                                          "s" = "Standing"))

treez <- treez %>% mutate(site_h_c = recode(site_h_c,
                                          c = "Control Site",
                                          C = "Control Site",
                                          H = "Hurricane Site"))
t <- sapply(treez, unique)
t$substrate_g_l_p_m

treez %>% 
  group_by(substrate_g_l_p_m) %>%
  summarise(count = n())

treez <-  treez %>% mutate(substrate_g_l_p_m = recode(substrate_g_l_p_m,
                          "N/A" = NULL,
                          "M (rock)" = "M",
                          "g" = "G",
                          l = "L",
                          m = "M",
                          p = "P"
                          

                     
                   )) 
```
	1. azimuths of fallen trees in the hurricane site (graph)
	2. azimuths of fallen trees in the control site (graph)

```{r}
c("North")

treez %>% filter( standing_fallen == "Fallen") %>%
  ggplot(aes(x = degrees, fill = genus)) +
  geom_histogram(binwidth = 24)+
  facet_wrap(~site_h_c, ncol = 1)+
  scale_x_continuous(breaks = c(0, 90, 180, 270, 360), labels = c("North (0)", "East(90)", "South(180)", "West(270)", "North(360)"))+xlab(NULL)
```
at the hurricane site, genus of fallen trees as a percentage of all fallen trees

```{r find proportions }
#fallen at hurricane 
fhp <- 
  treez %>%
  filter(site_h_c == "Hurricane Site") %>%
  filter(standing_fallen == "Fallen") %>%
  group_by(genus) %>%
  summarise(count = n())%>%
  mutate(Proportion = (count/sum(count)) %>% signif(digits = 2))

#standing hurricane 

shp <-
  treez %>%
  filter(site_h_c == "Hurricane Site") %>%
  filter(standing_fallen == "Standing") %>%
  group_by(genus) %>%
  summarise(count = n())%>%
  mutate(Proportion = (count/sum(count)) %>% signif(digits = 2))

#control fallen
fcp <- 
  treez %>%
  filter(site_h_c == "Control Site") %>%
  filter(standing_fallen == "Fallen") %>%
  group_by(genus) %>%
  summarise(count = n())%>%
  mutate(Proportion = (count/sum(count)) %>% signif(digits = 2))

#Control standing
scp <- 
  treez %>%
  filter(site_h_c == "Control Site") %>%
  filter(standing_fallen == "Standing") %>%
  group_by(genus) %>%
  summarise(count = n())%>%
  mutate(Proportion = 
           (count/sum(count)) %>% signif(digits = 2))

```
density (number per hectare) of seedlings, saplings, and trees of each genus growing on ground, fallen log, pit, or tip up mound in the affected site (graph)
```{r hurricane trees density on substrate}
h_ha_by_substrate <-
  treez %>% 
  filter(site_h_c == "Hurricane Site") %>%
  group_by(substrate_g_l_p_m)%>%
  summarise(numplot = length(unique(plot_number))) %>%
  mutate(ha = ((numplot * 100)/10000))

h_tree_count_by_genus_substrate <- 
  treez %>% 
  filter(site_h_c == "Hurricane Site") %>%
  filter(standing_fallen == "Standing") %>%
  group_by(substrate_g_l_p_m, genus) %>%
  summarise(n = n()) 

h_density <- left_join(h_tree_count_by_genus_substrate, h_ha_by_substrate, by = "substrate_g_l_p_m")

h_density<- h_density %>% mutate( density = (n / ha))


h_density %>% 
  ggplot() +
  geom_bar(aes(x = substrate_g_l_p_m, y = density, fill = genus), stat = "identity")
```


```{r control trees density on substrate}
c_ha_by_substrate <-
  treez %>% 
  filter(site_h_c == "Control Site") %>%
  group_by(substrate_g_l_p_m)%>%
  summarise(numplot = length(unique(plot_number))) %>%
  mutate(ha = ((numplot * 100)/10000))

c_tree_count_by_genus_substrate <- 
  treez %>% 
  filter(site_h_c == "Control Site") %>%
  filter(standing_fallen == "Standing") %>%
  group_by(substrate_g_l_p_m, genus) %>%
  summarise(n = n()) 

c_density <- left_join(c_tree_count_by_genus_substrate, c_ha_by_substrate, by = "substrate_g_l_p_m")

c_density<- c_density %>% mutate( density = (n / ha))


c_density %>% 
  ggplot() +
  geom_bar(aes(x = substrate_g_l_p_m, y = density, fill = genus), stat = "identity")
```
```{r clean seedling sapling data}
liltrees%>% sapply(unique)

liltrees %>% group_by(genus) %>% summarise( n = n())

liltrees <- liltrees %>% mutate( genus = recode(genus,
                                          B = "unknown",
                                          Beach = "beech",
                                          Beech= "beech",
                                          BEACH = "beech",
                                          hb = "hornbeam",
                                          "hornbea," = "hornbeam",
                                          "Bir ch" = "birch",
                                          Birch = "birch",
                                          "Dead?" = "unknown",
                                          "Oak" = "oak",
                                          "OAK" = "oak",
                                          oube = "unknown",
                                          "PB" = "birch",
                                          "Pine" = "pine",
                                          RM = "maple",
                                          SM = "maple",
                                          Maple = "maple",
                                          Unknown = "unknown",
                                          WP = "pine"
))


 liltrees$standing_fallen %>% unique()



liltrees <- liltrees %>% mutate(site_h_c = recode(site_h_c,
                                            c = "Control Site",
                                            C = "Control Site",
                                            H = "Hurricane Site"))
t <- sapply(liltrees, unique)
t$substrate_g_l_p_m

liltrees %>% 
  group_by(substrate_g_l_p_m) %>%
  summarise(count = n())

liltrees <-  liltrees %>% mutate(substrate_g_l_p_m = recode(substrate_g_l_p_m,
                                                      "N/A" = NULL,
                                                      "M (rock)" = "M",
                                                      "g" = "G",
                                                      l = "L",
                                                      m = "M",
                                                      p = "P"
                                                      
                                                      
                                                      
)) 

liltrees%>% sapply(unique)

```

```{r}
liltrees %>% 
  filter(site_h_c == "Hurricane Site") %>%
  group_by(substrate_g_l_p_m)%>%
  summarise(numplot = length(unique(plot_number))) %>%
  mutate(ha = ((numplot * 100)/10000))

```


```{r hurricane seedling density on substrate}
lh_ha_by_substrate <-
  liltrees %>% 
  filter(site_h_c == "Hurricane Site") %>%
  group_by(substrate_g_l_p_m)%>%
  summarise(numplot = length(unique(plot_number))) %>%
  mutate(ha = ((numplot * 100)/10000))

lh_tree_count_by_genus_substrate <- 
  liltrees %>% 
  filter(site_h_c == "Hurricane Site") %>%
 
  group_by(substrate_g_l_p_m, genus) %>%
  summarise(seed_tot = sum(seedlin_count,na.rm = TRUE), sap_tot = sum(sap_count,na.rm = TRUE)) 

lh_density <- left_join(lh_tree_count_by_genus_substrate, lh_ha_by_substrate, by = "substrate_g_l_p_m")

lh_density<- lh_density %>% mutate( sap_density = (sap_tot / ha), seed_density = (seed_tot / ha))


lh_density %>% 
  ggplot() +
  geom_bar(aes(x = substrate_g_l_p_m, y = density, fill = genus), stat = "identity")
```

```{r hurricane seedling density on substrate}
ch_ha_by_substrate <-
  liltrees %>% 
  filter(site_h_c == "Control Site") %>%
  group_by(substrate_g_l_p_m)%>%
  summarise(numplot = length(unique(plot_number))) %>%
  mutate(ha = ((numplot * 100)/10000))

ch_tree_count_by_genus_substrate <- 
  liltrees %>% 
  filter(site_h_c == "Control Site") %>%
  
  group_by(substrate_g_l_p_m, genus) %>%
  summarise(seed_tot = sum(seedlin_count,na.rm = TRUE), sap_tot = sum(sap_count,na.rm = TRUE)) 

ch_density <- left_join(ch_tree_count_by_genus_substrate, ch_ha_by_substrate, by = "substrate_g_l_p_m")

ch_density<- ch_density %>%  mutate( sap_density = (sap_tot / ha), seed_density = (seed_tot / ha))



```

```{r}
#join all four density dfs into one df

## add site back into each
ch_density <- ch_density %>% mutate(site = "control")
lh_density <- lh_density %>% mutate(site = "hurricane")
h_density <- h_density %>% mutate(site = "hurricane")
c_density <- c_density %>% mutate(site = "control")



rbind(ch_density,lh_density,c_density,h_density) %>%
  ggplot() +
  geom_bar(aes(x = substrate_g_l_p_m, y = density, fill = genus), stat = "identity") + facet_wrap(~site)
```






```{r}
treez  %>%
  ggplot(aes( x = site_h_c, fill = genus))+ geom_bar()+ facet_wrap(~standing_fallen, ncol =1)

```

